cmm-apps-android/EsmorgaAndroid

designsystem/src/main/java/cmm/apps/designsystem/EsmorgaButton.kt
designsystem/src/main/java/cmm/apps/designsystem/EsmorgaText.kt
view/src/main/java/cmm/apps/esmorga/view/theme/Theme.kt
view/src/main/java/cmm/apps/esmorga/view/theme/Type.kt
view/src/test/java/cmm/apps/esmorga/view/screenshot/BaseScreenshotTest.kt
view/src/test/snapshots/images/cmm.apps.esmorga.view.screenshot.eventList_EventListViewScreenshotTest_eventListView_lightTheme_data.png
view/src/test/snapshots/images/cmm.apps.esmorga.view.screenshot.eventdetails_EventDetailsScreenshotTest_eventDetailsView_lightTheme_data.png
view/src/test/snapshots/images/cmm.apps.esmorga.view.screenshot.eventdetails_EventDetailsScreenshotTest_eventDetailsView_lightTheme_no_location.png

MOB-153: Fix color scheme in texts.

---

datasource-remote/src/main/java/cmm/apps/esmorga/datasource_remote/event/mapper/RemoteEventMapper.kt
view/src/main/java/cmm/apps/esmorga/view/eventlist/mapper/EventListUiMapper.kt

It's not possible to pass an url in navigation compose, it needs to be encoded.

fix navigation when event includes url

---

.github/tmp/branch.txt
app/build.gradle.kts
app/src/main/AndroidManifest.xml
build.gradle.kts
gradle/libs.versions.toml
view/build.gradle.kts
view/src/main/AndroidManifest.xml

- Added required changes in `build.gradle` (app and project) to integrate Firebase.
- Included the `google-services.json` file for Firebase configuration.
- Configured Firebase initialization in AndroidManifest.xml.
This enables Firebase Analytics and other Firebase services in the app.
Link: https://mobilemakers.atlassian.net/browse/MOB-232

Firebase Integration in the Project

---

.github/tmp/branch.txt
datasource-remote/build.gradle.kts
datasource-remote/src/main/AndroidManifest.xml
datasource-remote/src/main/java/cmm/apps/esmorga/datasource_remote/api/ExceptionHandler.kt
datasource-remote/src/main/java/cmm/apps/esmorga/datasource_remote/di/RemoteDIModule.kt
datasource-remote/src/main/java/cmm/apps/esmorga/datasource_remote/event/EventRemoteDatasource.kt
datasource-remote/src/main/java/cmm/apps/esmorga/datasource_remote/user/UserRemoteDatasource.kt
datasource-remote/src/main/java/cmm/apps/esmorga/datasource_remote/util/ConnectivityUtils.kt
datasource-remote/src/test/java/cmm/apps/esmorga/datasource_remote/event/EventRemoteDatasourceImplTest.kt
datasource-remote/src/test/java/cmm/apps/esmorga/datasource_remote/user/UserRemoteDatasourceImplTest.kt
datasource-remote/src/test/java/cmm/apps/esmorga/datasource_remote/util/ConnectivityUtilsTest.kt
gradle/libs.versions.toml
view/build.gradle.kts

MOB-233 - Error managment - No connectivity

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/profile/ProfileView.kt
view/src/test/snapshots/images/cmm.apps.esmorga.view.screenshot.profile_ProfileViewScreenshotTest_profileView_lightTheme_logged.png

Lastname is now showed in de profile screen

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/profile/ProfileView.kt
view/src/main/res/values/colors.xml
view/src/test/java/cmm/apps/esmorga/view/screenshot/profile/ProfileLogOutDialogViewScreenshotTest.kt
view/src/test/snapshots/images/cmm.apps.esmorga.view.screenshot.profile_ProfileLogOutDialogViewScreenshotTest_logoutDialog_default.png

Changed the appearance of the alert dialog when we log out from the profile and created a test screenshot

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/eventdetails/EventDetailsView.kt
view/src/main/java/cmm/apps/esmorga/view/login/LoginView.kt

MOB-248 - fix blank space at the bottom in login screen and event detail screen

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/profile/ProfileView.kt
view/src/test/snapshots/images/cmm.apps.esmorga.view.screenshot.profile_ProfileViewScreenshotTest_profileView_lightTheme_logged.png

https://mobilemakers.atlassian.net/jira/software/projects/MOB/boards/1?selectedIssue=MOB-285

Change password button hidden for release 1

---

designsystem/src/main/java/cmm/apps/designsystem/EsmorgaRow.kt
designsystem/src/main/java/cmm/apps/designsystem/EsmorgaText.kt
view/src/main/java/cmm/apps/esmorga/view/profile/ProfileView.kt

https://mobilemakers.atlassian.net/jira/software/projects/MOB/boards/1?selectedIssue=MOB-282

Created EsmorgaRow component and added to profile

---

.github/tmp/branch.txt
designsystem/src/main/java/cmm/apps/designsystem/EsmorgaRow.kt

https://mobilemakers.atlassian.net/browse/MOB-291

Modified caption width and removed unnecessary import

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/password/ResetPasswordView.kt
view/src/main/java/cmm/apps/esmorga/view/password/ResetPasswordViewModel.kt
view/src/test/java/cmm/apps/esmorga/view/screenshot/resetPassword/ResetPasswordViewScreenShotTest.kt
view/src/test/java/cmm/apps/esmorga/view/viewmodel/resetPassword/ResetPasswordViewModelTest.kt

MOB-309 - The "required field" text in the inline error is displayed and removed incorrectly.

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/password/model/ResetPasswordUiState.kt

MOB-312 - The button is activated even with the second field empty

---

.github/tmp/branch.txt
app/build.gradle.kts

MOB-320 - Update main version

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/eventdetails/EventDetailsView.kt
view/src/main/java/cmm/apps/esmorga/view/eventdetails/EventDetailsViewModel.kt
view/src/main/java/cmm/apps/esmorga/view/eventdetails/model/EventDetailsUiState.kt
view/src/main/java/cmm/apps/esmorga/view/navigation/Navigation.kt
view/src/test/java/cmm/apps/esmorga/view/viewmodel/eventdetails/EventDetailsViewModelTest.kt

MOB-328 - Mark Event Location

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/password/RecoverPasswordView.kt

https://mobilemakers.atlassian.net/jira/software/projects/MOB/boards/1?selectedIssue=MOB-330

ANDROID - Snackbar is hide under keyboard solved

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/profile/ProfileView.kt
view/src/test/snapshots/images/cmm.apps.esmorga.view.screenshot.profile_ProfileViewScreenshotTest_profileView_lightTheme_logged.png
view/src/test/snapshots/images/cmm.apps.esmorga.view.screenshot.profile_ProfileViewScreenshotTest_profileView_lightTheme_not_logged.png

https://mobilemakers.atlassian.net/jira/software/projects/MOB/boards/1?selectedIssue=MOB-331

MOB-331 Show password button displayed and updated screenshot test

---

.github/tmp/branch.txt
app/src/test/java/cmm/apps/esmorga/component/mock/UserDataMock.kt
data/src/main/java/cmm/apps/esmorga/data/user/mapper/UserDataMapper.kt
data/src/main/java/cmm/apps/esmorga/data/user/model/UserDataModel.kt
data/src/test/kotlin/cmm/apps/esmorga/data/mock/UserDataMock.kt
data/src/test/kotlin/cmm/apps/esmorga/data/user/UserRepositoryImplTest.kt
datasource-local/schemas/cmm.apps.esmorga.datasource_local.database.EsmorgaDatabase/3.json
datasource-local/src/main/java/cmm/apps/esmorga/datasource_local/database/EsmorgaDatabase.kt
datasource-local/src/main/java/cmm/apps/esmorga/datasource_local/database/EsmorgaDatabaseHelper.kt
datasource-local/src/main/java/cmm/apps/esmorga/datasource_local/user/mapper/LocalUserMapper.kt
datasource-local/src/main/java/cmm/apps/esmorga/datasource_local/user/model/UserLocalModel.kt
datasource-local/src/test/java/cmm/apps/esmorga/datasource_local/mock/UserLocalMock.kt
datasource-remote/src/main/java/cmm/apps/esmorga/datasource_remote/user/mapper/RemoteUserMapper.kt
datasource-remote/src/main/java/cmm/apps/esmorga/datasource_remote/user/model/UserRemoteModel.kt
datasource-remote/src/test/java/cmm/apps/esmorga/datasource_remote/mock/UserRemoteMock.kt
domain/src/main/java/cmm/apps/esmorga/domain/user/model/User.kt
domain/src/test/kotlin/cmm/apps/esmorga/domain/mock/UserDomainMock.kt
view/src/test/java/cmm/apps/esmorga/view/screenshot/profile/ProfileViewScreenshotTest.kt
view/src/test/java/cmm/apps/esmorga/view/viewmodel/eventdetails/EventDetailsViewModelTest.kt
view/src/test/java/cmm/apps/esmorga/view/viewmodel/mock/LoginViewMock.kt
view/src/test/java/cmm/apps/esmorga/view/viewmodel/profile/ProfileViewModelTest.kt

MOB - 290 -  Admin role management

---

.github/tmp/branch.txt
view/src/main/AndroidManifest.xml
view/src/main/java/cmm/apps/esmorga/view/createevent/CreateEventFormScreen.kt
view/src/main/java/cmm/apps/esmorga/view/login/LoginView.kt
view/src/main/java/cmm/apps/esmorga/view/password/RecoverPasswordView.kt
view/src/main/java/cmm/apps/esmorga/view/password/ResetPasswordView.kt
view/src/main/java/cmm/apps/esmorga/view/registration/RegistrationView.kt

Fix to be able to hide keyboard tapping on screen background in registration form screen.

MOB-356 - Keyboard stucked on Login and Registration screen

---

.github/tmp/branch.txt
domain/src/main/java/cmm/apps/esmorga/domain/user/model/User.kt

https://mobilemakers.atlassian.net/browse/MOB-357

MOB-357 - Wrong error message on password field on registration screen

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/createeventtype/CreateEventFormTypeScreen.kt
view/src/main/res/values-es-rES/strings.xml
view/src/main/res/values/strings.xml

MOB-367 - Typo in the "Event Type" title tag

---

.github/tmp/branch.txt
view/src/main/java/cmm/apps/esmorga/view/eventdetails/mapper/EventDetailsUiMapper.kt
view/src/main/java/cmm/apps/esmorga/view/eventlist/EventListViewModel.kt
view/src/test/java/cmm/apps/esmorga/view/viewmodel/eventList/EventListViewModelTest.kt

MOB-386 - The app crashes when enter to event details screen
